apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: locust-worker
  template:
    metadata:
      labels:
        app: locust-worker
    spec:
      containers:
      - name: locust-worker
        image: varunregistery02.azurecr.io/locustimagevarun:latest
        env:
        - name: LOCUST_MODE
          value: worker
        - name: LOCUST_MASTER_HOST
          value: locust-master
        - name: LOCUST_FILE
          value: /mnt/locustfile.py
