apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-slave
spec:
  replicas: 2  # Adjust the number of replicas based on your requirements
  selector:
    matchLabels:
      app: locust-slave
  template:
    metadata:
      labels:
        app: locust-slave
    spec:
      volumes:
      - name: locust-tasks
        configMap:
          name: locust-tasks
      containers:
      - name: locust-slave
        image: locustio/locust
        command: ["/bin/sh"]
        args: ["-c", "locust --worker --master-host=locust-master --host=https://drm-staging.saavn.com"]
        volumeMounts:
        - mountPath: /locust-tasks
          name: locust-tasks
